/** Produce the checked-in, offline browser dependency from the pinned npm lockfile. */
import { build } from "esbuild";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = fileURLToPath(new URL("../", import.meta.url));
const outputDirectory = path.join(root, "js/vendor");
const checkOnly = process.argv.includes("--check");
const tonalPackage = JSON.parse(
  await readFile(path.join(root, "node_modules/tonal/package.json"), "utf8"),
);
if (tonalPackage.version !== "6.4.3")
  throw new Error("Expected the pinned tonal@6.4.3. Run npm ci.");

const result = await build({
  absWorkingDir: root,
  stdin: {
    contents:
      'export * as Chord from "@tonaljs/chord"; export * as Note from "@tonaljs/note"; export * as Scale from "@tonaljs/scale";',
    resolveDir: root,
    sourcefile: "tonal-entry.js",
  },
  outfile: path.join(outputDirectory, "tonal.js"),
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2022",
  minify: true,
  charset: "utf8",
  legalComments: "none",
  write: false,
  metafile: true,
  banner: {
    js: "/*! Tonal 6.4.3 · MIT · https://github.com/tonaljs/tonal · License: ./tonal.LICENSE.txt */",
  },
});

const bundledInputs = Object.values(result.metafile.outputs).flatMap((output) =>
  Object.entries(output.inputs)
    .filter(([, details]) => details.bytesInOutput > 0)
    .map(([input]) => input),
);
const includedPackages = [
  ...new Set([
    "tonal",
    ...bundledInputs
      .map(
        (input) => input.match(/node_modules\/(tonal|@tonaljs\/[^/]+)\//)?.[1],
      )
      .filter(Boolean),
  ]),
].sort();
const projectLicense = (
  await readFile(path.join(root, "node_modules/tonal/LICENSE"), "utf8")
).trim();
const notices = new Map();
for (const packageName of includedPackages) {
  const directory = path.join(root, "node_modules", packageName);
  const metadata = JSON.parse(
    await readFile(path.join(directory, "package.json"), "utf8"),
  );
  if (metadata.license !== "MIT")
    throw new Error(`Review the changed license for ${packageName}.`);
  const license = (
    await readFile(path.join(directory, "LICENSE"), "utf8").catch((error) => {
      if (error.code === "ENOENT") return projectLicense;
      throw error;
    })
  ).trim();
  const packages = notices.get(license) || [];
  packages.push(`${packageName}@${metadata.version}`);
  notices.set(license, packages);
}
const licenseText = `Tonal browser bundle: third-party notices\nGenerated by npm run vendor:tonal from the pinned npm lockfile.\n\n${[...notices].map(([license, packages]) => `Included packages:\n${packages.map((name) => `- ${name}`).join("\n")}\n\n${license}`).join("\n\n---\n\n")}\n`;
const files = [
  [path.join(outputDirectory, "tonal.js"), result.outputFiles[0].text],
  [path.join(outputDirectory, "tonal.LICENSE.txt"), licenseText],
];
await mkdir(outputDirectory, { recursive: true });
for (const [filename, contents] of files) {
  if (checkOnly) {
    const current = await readFile(filename, "utf8").catch(() => null);
    if (current !== contents)
      throw new Error(
        `${path.relative(root, filename)} is stale. Run npm run vendor:tonal and commit both vendor files.`,
      );
  } else {
    await writeFile(filename, contents);
  }
}
console.log(
  checkOnly
    ? "Tonal bundle and license notices match the pinned dependencies."
    : `Tonal 6.4.3 bundled for offline use (${result.outputFiles[0].contents.length} bytes).`,
);
